version: "3"
services: 
  db: 
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - my_network 
  php:
    build: ./tkphp
    image: testxddd:latest
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - my_network
    working_dir: /usr/src/myapp/tp5/public
    command: php -S 0.0.0.0:80
    
networks:
    my_network:

                
