version: "3"
services: 
  db: 
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - /home/louis/database:/var/lib/mysql
    networks:
      - my_network 
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8081:80
    networks:
      - my_network
  php:
    image: tkphp:latest
    depends_on:
      - db
      - phpmyadmin
    volumes:
      - /home/louis/php/addcnwork:/usr/src/myapp
    ports:
      - 8080:80
    networks:
      - my_network
    working_dir: /usr/src/myapp
    command: php -S 0.0.0.0:80

    #tty: true
networks:
    my_network:

                
